### PR TITLE
day2 worker config base examples

### PR DESCRIPTION
**Pull request by jnunyez**
RAN worker nodes share some additional requirements that default MachineConfig settings do not satisfy. Some examples could be disable default timing service (Chronyd) to run PTP, enable SCTP kernel module. I would propose to put the common ones into this repo associated to a MachineConfigPool. In this way they can be consumed from any cluster located in any site. The parameter that could be patched are the labels used for the specific deployment.

### CODE REVIEW

**Comment by natifridman** [comment]
@jnunyez Could you please give some background for this in the description of this PR?

**Comment by jnunyez** [comment]
> @jnunyez Could you please give some background for this in the description of this PR?

 RAN worker nodes **share** some additional requirements that default MachineConfig settings do not satisfy. Some examples could be disable default timing service (Chronyd) to run PTP, enable SCTP kernel module. I would propose to put the common ones into this repo associated to a MachineConfigPool. In this way they can be consumed from any cluster located in any site. The parameter that could be patched are the labels used for the specific deployment.

**Review by natifridman — COMMENTED** [review]
Looks good. Could you please add a readme in the base folder to explain what configuration is included here and when we should use it?

**Review by novacain1 — APPROVED** [review]
LGTM

**Comment by jnunyez** [comment]
> Looks good. Could you please add a readme in the base folder to explain what configuration is included here and when we should use it?

Done.

**Comment by natifridman** [comment]
Need to rebase with main

**Pull request merged**
