### PR TITLE
fix resource values to avoid ArgoApp out-of-sync

### PR DESCRIPTION
**Pull request by jnunyez**

### CODE REVIEW

**Review by novacain1 — COMMENTED** [review]
Maybe I am tired.  Isn't 2000 millicores (2000m) the same thing as 2 CPUs?

**Comment by jnunyez** [comment]
> Maybe I am tired. Isn't 2000 millicores (2000m) the same thing as 2 CPUs?

The meaning is the same, but ocp reformats the values, e.g., 2000m will be changed to 2 when the manifest is applied. So when Argo compares when what is on gihub to sync state the ArgoApplicatio goes out-of-sync since '2000m' not equal to '2' stringwise.

**Comment by novacain1** [comment]
After discussion and a reference point:
https://github.com/argoproj/argo-cd/issues/132

Let's standardize on using the millicore nomenclature for fractional units and use whole integer values for cases where there are not requirements for fractional units.

**Review by novacain1 — APPROVED** [review]
LGTM, see comments

**Pull request merged**
